name: Daily Node Collector Job

on:
  schedule:
    - cron: '0 7 * * *'  # Daily at 7am UTC
  workflow_dispatch:     # Optional: manual trigger

jobs:
  run-node-collector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build container locally
        run: docker build -t node-collector .

      - name: Run container
        run: docker run --rm -e DATABASE_URL="${{ secrets.DATABASE_URL }}" node-collector
